-- The readers table follows the original schema in database/BangDB.pdf:
-- card_code, full_name, email, phone, address, card_status,
-- card_issued_at, card_expiry_date, active, created_at, updated_at.
--
-- Keep this baseline migration intentionally empty. ReaderManagement maps to
-- the original columns and must not add created_by_user_id, phone_number,
-- is_active, or card_expiry_at to readers.
