spring.application.name=library-management
server.port=${PORT:8080}

# Cho phép ứng dụng hoàn tất request đang xử lý trước khi dừng.
server.shutdown=graceful
spring.lifecycle.timeout-per-shutdown-phase=${SHUTDOWN_TIMEOUT:30s}
server.forward-headers-strategy=framework
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# không để update vì để update khi JPAentity không giống với bảng thì sẽ tạo ra cột mới
# spring.jpa.hibernate.ddl-auto=${DDL_AUTO:update}
spring.jpa.hibernate.ddl-auto=validate

# Flyway Configuration
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true
spring.flyway.baseline-version=0

spring.jpa.open-in-view=false

spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

security.jwt.secret=${JWT_SECRET}
security.jwt.access-token-expiration-ms=${JWT_ACCESS_TOKEN_EXPIRATION_MS:3600000}

server.error.include-message=never
server.error.include-binding-errors=never
server.error.include-stacktrace=never
server.error.include-exception=false
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=6MB
app.cors.allowed-origins=http://localhost:3000,http://127.0.0.1:3000

# giới hạn môi trường đang ở local/dev để chạy dataseeder thì chạy bằng $env:SPRING_PROFILES_ACTIVE="local"

# Cloudflare R2 Storage Configuration
cloud.r2.endpoint=${R2_ENDPOINT:https://8ab691aba9a8e084f6f68a2036b4a19a.r2.cloudflarestorage.com}
cloud.r2.access-key=${R2_ACCESS_KEY}
cloud.r2.secret-key=${R2_SECRET_KEY}
cloud.r2.bucket-name=${R2_BUCKET_NAME:library-management}
cloud.r2.public-url=${R2_PUBLIC_URL:https://pub-21b3e7ec426b49d29c3f815a5312ac5f.r2.dev}
