name: Backend CI

on:
  pull_request:
    branches: [develop]
  push:
    branches: [develop]

jobs:
  backend:
    name: Build Backend

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Grant execute permission
        run: chmod +x mvnw

      - name: Build & Verify
        env:
          DB_URL: jdbc:h2:mem:library_test;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=false
          DB_USERNAME: sa
          DB_PASSWORD: ""
          JWT_SECRET: MDEyMzQ1Njc4OTAxMjM0NTY3ODkwMTIzNDU2Nzg5MDE=
        run: ./mvnw clean verify